ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'RETURNED_FOR_COMPLETION';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'NOT_ACCEPTED';

ALTER TYPE "SLAStage" ADD VALUE IF NOT EXISTS 'COMPLETENESS';
